// qsys_top_s10_user_rst_clkgate_0.v

// Generated using ACDS version 23.4 66

`timescale 1 ps / 1 ps
module qsys_top_s10_user_rst_clkgate_0 (
		output wire  ninit_done  // ninit_done.reset
	);

	altera_s10_user_rst_clkgate s10_user_rst_clkgate_0 (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.reset
	);

endmodule
