// qsys_top_inst_clk_bfm_ip.v

// Generated using ACDS version 23.4 66

`timescale 1 ps / 1 ps
module qsys_top_inst_clk_bfm_ip #(
		parameter CLOCK_RATE = 50000000,
		parameter CLOCK_UNIT = 1
	) (
		output wire  clk  // clk.clk
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (CLOCK_RATE),
		.CLOCK_UNIT (CLOCK_UNIT)
	) qsys_top_inst_clk_bfm (
		.clk (clk)  //  output,  width = 1, clk.clk
	);

endmodule
